POST http://localhost:8060/api/accounts
Content-Type: application/json

{
  "id": "user1",
  "password": "1234",
  "name": "유저1",
  "email": "user1@gmail.com"
}

###
POST http://localhost:8060/api/accounts
Content-Type: application/json

{
  "id": "user2",
  "password": "1234",
  "name": "유저2",
  "email": "user2@gmail.com"
}

###
POST http://localhost:8060/api/accounts/login
Content-Type: application/json

{
  "id": "user1",
  "password": "1234"
}

###
PUT http://localhost:8060/api/accounts
Content-Type: application/json

{
  "id": "user2",
  "password": "12345",
  "name": "유저22",
  "email": "user22@gmail.com",
  "latestLoginDate": "2024-01-01",
  "accountState": "회원"
}

###
GET http://localhost:8060/api/accounts

###
GET http://localhost:8060/api/accounts/user1

###
DELETE http://localhost:8060/api/accounts/user1

###
DELETE http://localhost:8060/api/accounts/user2

